### ISSUE TITLE
Segments Not Evaluating Properly Unless Using Exactly Matches

### ISSUE THREAD

**Issue by matthewtpowers** [Flagsmith/flagsmith-ios-client#11]
We have created a segment to use to override the "off" switch on one of our flags.  When using "exactly matches" on the ios version number the flag successfully gets overridden and its "turned on". However when we use >= the override does not match.  My guess is there is something wrong and Flagsmith is  evaluating the version number as a string.

This is how we set the value in Flagsmiths system

```swift
let iosVersionTrait = Trait(key: "ios_version", value: BundleConfiguration.appVersion)
Flagsmith.shared.setTrait(iosVersionTrait, forIdentity: user.email.or(""), completion: { _ in })
```

**Comment by dabeeeenster** [comment]
Hi @matthewtpowers - is this on our SaaS product? If so can you contact support@flagsmith.com or hit us up on our Discord (https://discord.gg/hFhxNtXzgm) so we can look into what data we persisted on our backend? 

If this is self hosted, are you able to replicate with a free account on app.flagsmith.com so we can do the same?

Thanks!

**Comment by dabeeeenster** [comment]
Value was a string
