### ISSUE TITLE
Enabling a feature for a particular user is not working

### ISSUE THREAD

**Issue by elavarasantnl** [Flagsmith/flagsmith-ios-client#13]
When I tried to enable a feature for a particular user with user Traits, iOS client is always returning  enabled false.
<img width="848" alt="Screenshot 2022-01-03 at 10 54 09 AM" src="https://user-images.githubusercontent.com/96741601/147901618-8632dc38-06b4-4abb-aa97-2a84eb64eab8.png">

But when I tried using the test tool in the web ,it is returning enabled true.

<img width="1122" alt="Screenshot 2022-01-03 at 10 58 08 AM" src="https://user-images.githubusercontent.com/96741601/147901777-53536d3a-ef8c-4d79-a124-8246a10c983f.png">

Let me know if I am doing anything wrong?

**Comment by gagantrivedi** [comment]
Hi @elavarasantnl  to get feature values with trait/identity overrides you need to pass identity to `getFeatureFlags`
PS: here is the full signature:
```
  /// Get all feature flags (flags and remote config) optionally for a specific identity
  ///
  /// - Parameters:
  ///   - identity: ID of the user (optional)
  ///   - completion: Closure with Result which contains array of Flag objects in case of success or Error in case of failure
  public func getFeatureFlags(forIdentity identity: String? = nil,
                              completion: @escaping (Result<[Flag], Error>) -> Void) {
```

**Comment by elavarasantnl** [comment]
@gagantrivedi  even in that function it is enabled false only.
<img width="896" alt="Screenshot 2022-01-03 at 11 22 31 AM" src="https://user-images.githubusercontent.com/96741601/147902782-a623e95e-6b2a-4b72-905a-306f1b173a1c.png">

**Comment by gagantrivedi** [comment]
@elavarasantnl  it seems like "ask-counsellor" is the name of the feature? If yes, you need to pass the identity to  `getFeatureFlags` not feature name. I think you need to  pass `"2693770"`, i.e: identity identifier

**Comment by elavarasantnl** [comment]
@gagantrivedi Yes, it is working now. thanks
