### ISSUE TITLE
Traits should implement `UnknownTypeValue`

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith-ios-client#15]
Trait values can be one of four different data types:

- String
- Integer
- Float
- Boolean

We need to implement `UnknownTypeValue` for the Trait value so that the value is written and read with the correct type in the Flagsmith API.

**Comment by richardpiazza** [comment]
This ties into another PR that I was looking at creating... Digging through the API docs I didn't quite find an answer to the following:

* Do `Flag`s and `Trait`s always have a value associated to them, or can they be represented by nil/null/empty in the API?
* Also, are `String`, `Int`, `Float`, and `Bool` then only possible value types?

**Comment by matthewelwell** [comment]
Hi @richardpiazza, thanks for the questions here. Hopefully the following responses clear things up for you. 

> Do Flags and Traits always have a value associated to them, or can they be represented by nil/null/empty in the API?

Traits and Flags always 'have' a value from the API perspective, yes, although that value can be an empty string or null for example.

> Also, are String, Int, Float, and Bool then only possible value types?

Yes, that is correct.

**Comment by dabeeeenster** [comment]
Nice timing - we just pushed https://github.com/Flagsmith/flagsmith-ios-client/pull/16/files but if you have other aspects you would like to work on @richardpiazza we'd be happy for PRs!

**Comment by richardpiazza** [comment]
Thanks for the info @matthewelwell & @dabeeeenster. I'll probably hold my PR to see what the outcome of 16 is... Here's the direction I was headed: https://github.com/Flagsmith/flagsmith-ios-client/compare/main...richardpiazza:feature/typed-values?expand=1

Essentially replacing `UnknownTypeValue` with `TypedValue` and leaving flag and trait values `Optional` to indicate the presence of a expected(known) value type or nil. This also accounts for any backwards implementation that relies on `Trait.value` being a`String`.

**Comment by dabeeeenster** [comment]
Hi @richardpiazza - your PR is better in terms of backwards compatibility so happy to take this forward - is there anything more you want to add to it before we review it? Thanks for the contribution!
