### ISSUE TITLE
Bulk Uploading Identities and Traits

### ISSUE THREAD

**Issue by ctreffs** [Flagsmith/flagsmith-ios-client#23]
The documentation of Flagsmith states that there is an endpoint available for bulk uploading identities and their respective trait: https://docs.flagsmith.com/basic-features/managing-identities#bulk-uploading-identities-and-traits
Sadly though it is not currently available in the iOS SDK.
The current implementation only provides [`setTrait(_ trait: Trait, forIdentity identity: String)`](https://github.com/Flagsmith/flagsmith-ios-client/blob/95195e377658ba2774b8c795b7321b71509a3b1a/FlagsmithClient/Classes/Flagsmith.swift#L185), setting only one trait at a time.

The bulk option would be a welcome addition for our use case. 
Are there any plans to extend the API manager to support this call?

**Comment by dabeeeenster** [comment]
yep - this looks like a difficiency with the iOS SDK. Will get on it!

**Comment by ctreffs** [comment]
I'm sorry but there is no API exposed to call the `.postTraits` route with the SDK

**Comment by ctreffs** [comment]
I've added a PR for that https://github.com/Flagsmith/flagsmith-ios-client/pull/26

**Comment by dabeeeenster** [comment]
Thanks!
