### ISSUE TITLE
Privacy manifest and code signature

### ISSUE THREAD

**Issue by kesavaj** [Flagsmith/flagsmith-ios-client#49]
Starting from 1st may 2024, it is mandatory to have privacy manifest file and code signatures for all third party libraries used. Is this something you are working on. Please update

**Comment by dabeeeenster** [comment]
We are going to work on it and will have it released by end of month. We'll update the PR when it's finished. Thanks for opening the issue!

**Comment by antonmartinsson** [comment]
@dabeeeenster Any updates on this? 1st of May is coming up quick.

**Comment by matthewelwell** [comment]
This is being worked on here: https://github.com/Flagsmith/flagsmith-ios-client/pull/50, we're just working on splitting it out into smaller PRs.

**Comment by matthewelwell** [comment]
This is available since 3.6.0
